# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          environment:
            HEROKU_API_KEY: 7ab8dee2-8d05-4bda-8c32-bcdf1f1d4ea1
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
    - image: circleci/node:14.17.1-browsers
    steps:
    - checkout
    - run:
        name: npm install
        command: |
            cd vue-app
            npm install
    - run:
        name: Run Unit Tests
        command: |
            cd vue-app
            npm test