# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:14.17.1-browsers
    steps:
    - checkout
    - restore_cache:
        key: cache-{{ checksum "package.json" }}
    - run:
        name: npm install
        command: npm install
    - save_cache:
          paths:
              - ./node_modules
          key: cache-{{ checksum "package.json" }}
    - run:
        name: Run Unit Tests
        command: npm test